version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.40.1
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    restart: always
  exporter:
    image: prom/node-exporter:v1.4.0
    ports:
      - 9100:9100
    restart: always
  grafana:
    image: grafana/grafana:8.5.15
    ports:
      - 3000:3000
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./alertmanager:/etc/alertmanager
    ports:
      - 9093:9093
    restart: always

